## Import and inspect data

In [1]:
import pandas as pd

raw_df = pd.read_json("../data/raw/pluto_raw.json", orient="records", dtype=str)
df = raw_df.copy() # create a copy of the dataframe we can work with more freely

print("A look at the raw data...")
print()
df.info()
print()
df.describe()

A look at the raw data...

<class 'pandas.DataFrame'>
RangeIndex: 857235 entries, 0 to 857234
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   bbl      857235 non-null  str
 1   bct2020  857235 non-null  str
dtypes: str(2)
memory usage: 13.1 MB

                        bbl  bct2020
count                857235   857235
unique               857235     2322
top     4061730023.00000000  4089201
freq                      1     2559

## Rename & drop unnecessary columns

In [3]:
df = df.rename(columns={'bct2020': 'bct'}) # borough census tract
df.columns = df.columns.str.strip().str.lower() # standardize column names

print("Inspect row names")
print()
df.info()

Inspect row names

<class 'pandas.DataFrame'>
RangeIndex: 857235 entries, 0 to 857234
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   bbl     857235 non-null  str
 1   bct     857235 non-null  str
dtypes: str(2)
memory usage: 13.1 MB

## 3. Standardize data entries

In [6]:
print("test for null and duplicate rows pre-cleaning: ")
print("Null counts: ")
print(df.isnull().sum())
print(f"Starting duplicate rows: {df.duplicated().sum()}")

# format to simple 10 digit bbl to match LL84 data
df['bbl'] = df['bbl'].str.split('.').str[0] # since not a numeric, just split string at dec pt and take first part

print("Simple 10 digit bbl on first 3 entries: ")
df.head(3)

test for null and duplicate rows pre-cleaning:
Null counts:
bbl    0
bct    0
dtype: int64
Starting duplicate rows: 0
Simple 10 digit bbl on first 3 entries:

          bbl      bct
0  4061730023  4112300
1  4061730024  4112300
2  4061690026  4112300

## 4. Final check

In [7]:
print("data shape: ")
print(df.shape)
print()

print("null counts:")
print(df.isnull().sum())
print()

print("data types:")
print(df.dtypes)
print()

print("first few entries:")
df.head(10)

data shape:
(857235, 2)

null counts:
bbl    0
bct    0
dtype: int64

data types:
bbl    object
bct       str
dtype: object

first few entries:

          bbl      bct
0  4061730023  4112300
1  4061730024  4112300
2  4061690026  4112300
3  4061720001  4112300
4  4061720006  4112300
5  4061720019  4112300
6  4061760001  4112300
7  2026030083  2008300
8  4061760014  4112300
9  2036480043  2002800

## 5. Export data

In [8]:
df.to_pickle('../data/clean/pluto_cleaned.pkl')
print(f'Exported {len(df)} rows as pkl')
df.to_csv('../data/clean/pluto_cleaned.csv')
print(f'Exported {len(df)} rows as csv')

Exported 857235 rows as pkl
Exported 857235 rows as csv